### ISSUE TITLE
Remove shelljs dependency

### ISSUE THREAD

**Issue by stephenmichaelf** [Microsoft/vsts-node-api#157]

**Comment by bryanmacfarlane** [comment]
In here it's only a dev dependency right?  The shelljs concern wasn't about being stable, it was about some compat breaks in behaviour between 0.3 and 0.7 in the task-lib and since the task-lib delegates directly to shelljs in those case, it prevented us from consuming the new version because it would then indirectly change the customer task extensions calling those lib functions (and ultimately the consumers build definitions that depended on some copy pattern behavior).

**Comment by stephenmichaelf** [comment]
Yes it's only a dev dependency. My mistake I misunderstood what you were saying. I removed the description.

**Comment by bryanmacfarlane** [comment]
I think I'm fine keeping it as a dev dependency.  Convenient for scripting.
