### ISSUE TITLE
Support on-prem TFS

### ISSUE THREAD

**Issue by ArtGangsta** [Microsoft/vsts-node-api#184]
This project can easily support on-prem TFS, but it doesn't.   The name clearly says "vsts", first of all.  Although it has NTLM support, it doesn't have support for single sign-on.

Also, it assumes that the latest API version should be used, "i.e. 4.1-preview", but the latest on-prem version  of TFS doesn't support that yet.

**Comment by bryanmacfarlane** [comment]
The project supports on-prem via PAT token (TFS2015QU3+) and NTLM (supply user/pass).  It does not support integrated auth/single sign on.

The library negotiates the version to use with the service.  The 4.1-preview embedded in the client is just a way for the client to negotiate and tell the server the latest it knows about.  It will negotiate back down.  

Since it uses latest types (and contracts are append only) the data coming back will be what was supported/returned by that version of the server.  If you attempt to use a service with the latest client libraries that doesn't exist on the server you are working with, you will get the proper error message.

**Comment by ArtGangsta** [comment]
Well, I would like to use this library but with single sign-on support, which I will add in my own fork.   I'll post back here that's done.

**Comment by bryanmacfarlane** [comment]
We welcome PRs.  Thanks
