### ISSUE TITLE
Switch to common version scheme

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/vsts-node-api#88]
The .NET client libraries, VSS web extension SDK, etc follow a MajorVersion.Milestone.Patch-preview (e.g. 15.113.0-preview) versioning schema that aligns with on-premises releases and our overall API versioning. 

* `15.112.0`                 // API version 3.1, 2017 Update 1, M112 deployment
* `15.104.0-preview`   // API version 3.0-preview, 2017 pre-release, M104 deployment
* `14.102.0`                 // API version 2.3, 2015 Update 3, M102 deployment

The Node client should follow the same versioning scheme so consumers know how/where the package can be used (in general). Developers shouldn't have to try and figure out how "5.1" maps to our products/API versions.

At the same time, it would be good for the NPM package name to match the library name (`vsts-node-api`).

**Comment by bryanmacfarlane** [comment]
We discussed.  There is no figuring out how it maps.

With this api, it's simple, use latest and it supports all the back versions.  This scheme makes sense for the C# binaries that ship with VS.  But for this and the npm model, it adds more confusion because they think they have to use 14.x api to connect to a 14.x server.  What if I write a tool that can connect to any version that uses the api?  What do I use?  The answer is simple - latest.
